### ISSUE TITLE
глупый content-type

### ISSUE THREAD

**Issue by ed-asriyan** [M4MController/old_backend#1]
для всех методов, возвращающих json:
actual: `text/plain`
expected: `application/json`

**Comment by wolf1996** [comment]
https://github.com/M4MController/docs/wiki/%D0%90%D0%B4%D0%BC%D0%B8%D0%BD%D1%81%D1%82%D0%B2%D0%BE

**Comment by wolf1996** [comment]
Поправил всё это средствами nginx.
